from __future__ import annotations

from backend.multi_agent.agents.accessibility_agent import AccessibilityAgent
from backend.multi_agent.agents.authentication_agent import AuthenticationAgent
from backend.multi_agent.agents.navigation_agent import NavigationAgent
from backend.multi_agent.agents.performance_agent import PerformanceAgent
from backend.multi_agent.agents.visual_qa_agent import VisualQAAgent
