import { Bug, TestResult, AIFinding, LogEntry } from "./types";

// ── Seed bugs ──────────────────────────────────────────────────────

export const sampleBugs: Bug[] = [
  {
    id: "BUG-001",
    title: "Login Button Unresponsive on Mobile",
    description:
      "The login button does not trigger any action when clicked on screen sizes below 480px. The tap target appears too small and the click handler is not being invoked on touch devices.",
    severity: "critical",
    status: "open",
    url: "https://app.example.com/login",
    createdAt: "2026-04-28T10:30:00Z",
    assignedTo: "Sarah Chen",
    environment: "iOS Safari 17, iPhone 15 Pro",
    steps: [
      "Navigate to /login on a mobile device or emulator (< 480px viewport)",
      "Enter valid credentials in the email and password fields",
      "Tap the 'Sign In' button",
      "Observe that nothing happens — no loading state, no navigation, no error",
      "Check console for JavaScript errors related to touch events",
    ],
    logs: [
      { timestamp: "2026-04-28T10:30:12Z", level: "info", message: "Page loaded: /login (mobile viewport 375x812)" },
      { timestamp: "2026-04-28T10:30:15Z", level: "info", message: "User input detected: email field focused" },
      { timestamp: "2026-04-28T10:30:22Z", level: "warn", message: "Touch target size below minimum (44x44px): button.login-btn is 32x28px" },
      { timestamp: "2026-04-28T10:30:24Z", level: "error", message: "Click handler not firing on touch event — missing touchend listener" },
      { timestamp: "2026-04-28T10:30:24Z", level: "error", message: "Uncaught TypeError: Cannot read properties of undefined (reading 'submit')" },
    ],
  },
  {
    id: "BUG-002",
    title: "User Authentication Flow Fails Silently",
    description:
      "OAuth callback does not handle error states. When the provider returns an error, the user is redirected to the dashboard without authentication, causing subsequent API calls to fail with 401.",
    severity: "critical",
    status: "open",
    url: "https://app.example.com/auth/callback",
    createdAt: "2026-04-27T14:15:00Z",
    assignedTo: "Mike Johnson",
    environment: "Chrome 125, Windows 11",
    steps: [
      "Initiate OAuth login via Google",
      "Deny permissions on the consent screen",
      "Observe redirect to /dashboard instead of /login?error=denied",
      "Check network tab for 401 errors on API calls",
    ],
    logs: [
      { timestamp: "2026-04-27T14:15:01Z", level: "info", message: "OAuth redirect initiated" },
      { timestamp: "2026-04-27T14:15:05Z", level: "warn", message: "OAuth callback received with error parameter" },
      { timestamp: "2026-04-27T14:15:05Z", level: "error", message: "Error state not handled in auth callback handler" },
    ],
  },
  {
    id: "BUG-003",
    title: "Checkout API Timeout on Large Carts",
    description:
      "When a user has more than 50 items in their cart, the checkout API call times out after 30 seconds. The server-side cart validation is O(n²) and needs optimization.",
    severity: "high",
    status: "in-progress",
    url: "https://app.example.com/checkout",
    createdAt: "2026-04-26T09:00:00Z",
    assignedTo: "Alex Rivera",
    environment: "All browsers, Production",
    steps: [
      "Add 50+ items to cart",
      "Navigate to /checkout",
      "Click 'Place Order'",
      "Wait 30 seconds — request times out with 504 Gateway Timeout",
    ],
    logs: [
      { timestamp: "2026-04-26T09:00:10Z", level: "info", message: "Checkout initiated with 67 items" },
      { timestamp: "2026-04-26T09:00:40Z", level: "error", message: "Request timeout after 30000ms: POST /api/checkout" },
    ],
  },
  {
    id: "BUG-004",
    title: "CSS Grid Overlap in Product Gallery",
    description:
      "Product images overlap in the gallery view when viewport width is between 768px and 1024px. The CSS grid template columns are not properly responding to the breakpoint.",
    severity: "medium",
    status: "in-progress",
    url: "https://app.example.com/products",
    createdAt: "2026-04-25T16:45:00Z",
    assignedTo: "Lisa Park",
    environment: "iPad Air, Safari 17",
    steps: [
      "Navigate to /products",
      "Resize browser to 900px width",
      "Observe overlapping product cards in grid",
    ],
    logs: [
      { timestamp: "2026-04-25T16:45:02Z", level: "warn", message: "Grid layout overflow detected at viewport 900px" },
    ],
  },
  {
    id: "BUG-005",
    title: "Null Reference in Search Autocomplete",
    description:
      "Typing rapidly in the search box and then clearing it causes a null reference error. The debounced API call returns after the input has been cleared.",
    severity: "high",
    status: "open",
    url: "https://app.example.com/search",
    createdAt: "2026-04-24T11:20:00Z",
    assignedTo: "Sarah Chen",
    environment: "Firefox 126, macOS 15",
    steps: [
      "Click on the search bar",
      "Type 'test' rapidly",
      "Immediately clear the field with Ctrl+A → Delete",
      "Observe console error: Cannot read property 'map' of null",
    ],
    logs: [
      { timestamp: "2026-04-24T11:20:05Z", level: "info", message: "Search query: 'test'" },
      { timestamp: "2026-04-24T11:20:06Z", level: "error", message: "TypeError: Cannot read property 'map' of null at SearchResults.render" },
    ],
  },
  {
    id: "BUG-006",
    title: "API Gateway Timeout on Heavy Batch Operations",
    description:
      "Batch operations involving more than 100 records cause the API gateway to return 504 errors. The downstream service is not paginating requests.",
    severity: "high",
    status: "open",
    url: "https://app.example.com/admin/batch",
    createdAt: "2026-04-23T08:10:00Z",
    assignedTo: "Mike Johnson",
    environment: "All browsers, Staging & Production",
    steps: [
      "Navigate to Admin → Batch Operations",
      "Select 100+ records",
      "Click 'Process Batch'",
      "Observe 504 error after ~60 seconds",
    ],
    logs: [
      { timestamp: "2026-04-23T08:10:30Z", level: "error", message: "504 Gateway Timeout: POST /api/batch/process" },
    ],
  },
  {
    id: "BUG-007",
    title: "Database Connection Leak in Report Module",
    description:
      "The report generation module does not properly close database connections, leading to connection pool exhaustion after generating 20+ reports in a session.",
    severity: "critical",
    status: "resolved",
    url: "https://app.example.com/reports",
    createdAt: "2026-04-22T13:30:00Z",
    assignedTo: "Alex Rivera",
    environment: "Production, PostgreSQL 16",
    steps: [
      "Generate a report via Reports → New Report",
      "Repeat 20 times without refreshing the page",
      "Observe application becomes unresponsive",
      "Check server logs for connection pool errors",
    ],
    logs: [
      { timestamp: "2026-04-22T13:30:45Z", level: "error", message: "Connection pool exhausted: max connections (20) reached" },
      { timestamp: "2026-04-22T14:00:00Z", level: "success", message: "Fix deployed: connections now properly released after report generation" },
    ],
  },
  {
    id: "BUG-008",
    title: "S3 Image Upload Reliability Issue",
    description:
      "Image uploads to S3 fail intermittently with 'Network Error'. The retry logic does not handle multipart upload resumption correctly.",
    severity: "medium",
    status: "resolved",
    url: "https://app.example.com/profile/settings",
    createdAt: "2026-04-21T10:00:00Z",
    assignedTo: "Lisa Park",
    environment: "Chrome 125, slow 3G network simulation",
    steps: [
      "Go to Profile → Settings → Change Avatar",
      "Select an image > 2MB",
      "Simulate slow network (3G throttle in DevTools)",
      "Upload fails silently, no retry",
    ],
  },
  {
    id: "BUG-009",
    title: "Pricing Page Locale Currency Mismatch",
    description:
      "Users with EU locale settings see prices in USD instead of EUR. The locale detection falls back to defaults instead of reading Accept-Language header.",
    severity: "medium",
    status: "closed",
    url: "https://app.example.com/pricing",
    createdAt: "2026-04-20T16:45:00Z",
    assignedTo: "Alex Rivera",
    environment: "de-DE locale, Chrome 125",
    steps: [
      "Set browser language to de-DE",
      "Navigate to /pricing",
      "Observe prices displayed in $ instead of €",
    ],
  },
  {
    id: "BUG-010",
    title: "Accessibility: Missing ARIA Labels on Dashboard",
    description:
      "Interactive chart elements on the dashboard lack ARIA labels, making them inaccessible to screen readers. The SVG charts need role='img' and descriptive labels.",
    severity: "low",
    status: "open",
    url: "https://app.example.com/dashboard",
    createdAt: "2026-04-19T09:30:00Z",
    assignedTo: "Sarah Chen",
    environment: "NVDA + Chrome 125, Windows 11",
    steps: [
      "Enable screen reader (NVDA/VoiceOver)",
      "Navigate to /dashboard",
      "Tab through interactive elements",
      "Observe that charts are announced as 'graphic' with no description",
    ],
  },
  {
    id: "BUG-011",
    title: "WebSocket Disconnects Not Handled Gracefully",
    description:
      "When the WebSocket connection drops (e.g., network switch), the real-time notifications panel shows stale data without any reconnection attempt or user notification.",
    severity: "medium",
    status: "open",
    url: "https://app.example.com/notifications",
    createdAt: "2026-04-18T14:20:00Z",
    assignedTo: "Mike Johnson",
    environment: "All browsers",
    steps: [
      "Open notifications panel",
      "Disconnect network for 5 seconds",
      "Reconnect network",
      "Observe: no reconnection, stale data shown",
    ],
  },
  {
    id: "BUG-012",
    title: "Footer Links Return 404 on Production",
    description:
      "Several footer links (Privacy Policy, Terms of Service) point to staging URLs that return 404 on production builds.",
    severity: "low",
    status: "closed",
    url: "https://app.example.com",
    createdAt: "2026-04-17T08:10:00Z",
    assignedTo: "Lisa Park",
    environment: "Production, all browsers",
    steps: [
      "Scroll to footer",
      "Click 'Privacy Policy'",
      "Observe 404 page",
    ],
  },
];

// ── Seed test results ──────────────────────────────────────────────

export const sampleTestResults: TestResult[] = [
  {
    id: "TEST-001",
    url: "https://app.example.com/login",
    status: "failed",
    timestamp: "2026-04-28T10:28:00Z",
    duration: 3420,
    bugId: "BUG-001",
    details: "Login button tap target below 44px minimum on mobile viewport.",
    testType: "full",
    streamLogs: [
      { time: "00:00", level: "info", msg: "Initializing Automated Intelligence Probe..." },
      { time: "00:01", level: "info", msg: "Connecting to https://app.example.com/login..." },
      { time: "00:02", level: "success", msg: "Connection established. Starting scan..." },
      { time: "00:03", level: "info", msg: "Phase 1: DOM structure analysis..." },
      { time: "00:04", level: "info", msg: "Phase 2: JavaScript execution monitoring..." },
      { time: "00:05", level: "warn", msg: "Touch target size below minimum (44x44px): button.login-btn is 32x28px" },
      { time: "00:06", level: "info", msg: "Phase 3: Network request analysis..." },
      { time: "00:07", level: "info", msg: "Phase 4: Accessibility audit running..." },
      { time: "00:08", level: "error", msg: "Critical issue found! Login button unresponsive on mobile viewports < 480px" },
      { time: "00:09", level: "error", msg: "Bug BUG-001 created: Login Button Unresponsive on Mobile" },
      { time: "00:10", level: "info", msg: "Scan complete. Duration: 3.4s" },
    ],
  },
  {
    id: "TEST-002",
    url: "https://app.example.com/auth/callback",
    status: "failed",
    timestamp: "2026-04-27T14:10:00Z",
    duration: 5100,
    bugId: "BUG-002",
    details: "OAuth error callback not handled — user redirected without auth.",
    testType: "full",
    streamLogs: [
      { time: "00:00", level: "info", msg: "Initializing Automated Intelligence Probe..." },
      { time: "00:01", level: "info", msg: "Connecting to https://app.example.com/auth/callback..." },
      { time: "00:02", level: "success", msg: "Connection established. Starting scan..." },
      { time: "00:03", level: "info", msg: "Phase 1: OAuth flow simulation..." },
      { time: "00:04", level: "warn", msg: "OAuth callback received error parameter but no error handler found" },
      { time: "00:05", level: "error", msg: "User redirected to /dashboard without valid auth token" },
      { time: "00:06", level: "error", msg: "401 Unauthorized on subsequent API calls" },
      { time: "00:07", level: "error", msg: "Bug BUG-002 created: User Authentication Flow Fails Silently" },
      { time: "00:08", level: "info", msg: "Scan complete. Duration: 5.1s" },
    ],
  },
  {
    id: "TEST-003",
    url: "https://app.example.com/checkout",
    status: "failed",
    timestamp: "2026-04-26T08:55:00Z",
    duration: 31000,
    bugId: "BUG-003",
    details: "Checkout API timeout with 67 cart items.",
    testType: "ai",
    streamLogs: [
      { time: "00:00", level: "info", msg: "Initializing AI Deep Scan..." },
      { time: "00:01", level: "info", msg: "Connecting to https://app.example.com/checkout..." },
      { time: "00:02", level: "success", msg: "Connection established. Populating cart with 67 items..." },
      { time: "00:05", level: "info", msg: "Phase 1: Cart validation performance test..." },
      { time: "00:15", level: "warn", msg: "Response time exceeding 15s threshold..." },
      { time: "00:25", level: "warn", msg: "Server response still pending at 25s..." },
      { time: "00:30", level: "error", msg: "504 Gateway Timeout: POST /api/checkout" },
      { time: "00:31", level: "error", msg: "Bug BUG-003 created: Checkout API Timeout on Large Carts" },
      { time: "00:31", level: "info", msg: "Scan complete. Duration: 31.0s" },
    ],
  },
  {
    id: "TEST-004",
    url: "https://app.example.com/about",
    status: "passed",
    timestamp: "2026-04-28T09:00:00Z",
    duration: 1200,
    details: "All elements rendered correctly. No console errors.",
    testType: "full",
    streamLogs: [
      { time: "00:00", level: "info", msg: "Initializing Automated Intelligence Probe..." },
      { time: "00:01", level: "info", msg: "Connecting to https://app.example.com/about..." },
      { time: "00:02", level: "success", msg: "Connection established. Starting scan..." },
      { time: "00:03", level: "info", msg: "Phase 1: DOM structure analysis — all elements rendered" },
      { time: "00:04", level: "info", msg: "Phase 2: No JavaScript errors detected" },
      { time: "00:05", level: "info", msg: "Phase 3: All images have alt text" },
      { time: "00:06", level: "success", msg: "All checks passed. No critical issues detected." },
      { time: "00:06", level: "success", msg: "Scan complete. Duration: 1.2s" },
    ],
  },
  {
    id: "TEST-005",
    url: "https://app.example.com/blog",
    status: "passed",
    timestamp: "2026-04-27T16:30:00Z",
    duration: 2100,
    details: "Blog listing and pagination working as expected.",
    testType: "full",
    streamLogs: [
      { time: "00:00", level: "info", msg: "Initializing Automated Intelligence Probe..." },
      { time: "00:01", level: "info", msg: "Connecting to https://app.example.com/blog..." },
      { time: "00:02", level: "success", msg: "Connection established. Starting scan..." },
      { time: "00:03", level: "info", msg: "Testing pagination: page 1 → page 2 → page 3" },
      { time: "00:04", level: "info", msg: "All pagination links working correctly" },
      { time: "00:05", level: "success", msg: "All checks passed." },
      { time: "00:05", level: "success", msg: "Scan complete. Duration: 2.1s" },
    ],
  },
  {
    id: "TEST-006",
    url: "https://app.example.com/contact",
    status: "passed",
    timestamp: "2026-04-26T12:00:00Z",
    duration: 1800,
    details: "Contact form validation and submission OK.",
    testType: "full",
    streamLogs: [
      { time: "00:00", level: "info", msg: "Initializing Automated Intelligence Probe..." },
      { time: "00:01", level: "info", msg: "Connecting to https://app.example.com/contact..." },
      { time: "00:02", level: "success", msg: "Connection established. Starting scan..." },
      { time: "00:03", level: "info", msg: "Testing form validation: empty submit → error shown ✓" },
      { time: "00:04", level: "info", msg: "Testing form validation: valid input → 200 OK ✓" },
      { time: "00:05", level: "success", msg: "All checks passed." },
      { time: "00:05", level: "success", msg: "Scan complete. Duration: 1.8s" },
    ],
  },
  {
    id: "TEST-007",
    url: "https://app.example.com/pricing",
    status: "failed",
    timestamp: "2026-04-25T16:40:00Z",
    duration: 2400,
    bugId: "BUG-009",
    details: "Currency mismatch for EU locale — showing USD instead of EUR.",
    testType: "accessibility",
    streamLogs: [
      { time: "00:00", level: "info", msg: "Initializing Accessibility Probe..." },
      { time: "00:01", level: "info", msg: "Connecting to https://app.example.com/pricing..." },
      { time: "00:02", level: "success", msg: "Connection established. Setting locale: de-DE..." },
      { time: "00:03", level: "info", msg: "Testing i18n locale detection..." },
      { time: "00:04", level: "warn", msg: "Accept-Language header not being read by pricing service" },
      { time: "00:05", level: "error", msg: "Currency displayed as USD — expected EUR for de-DE locale" },
      { time: "00:06", level: "error", msg: "Bug BUG-009 created: Pricing Page Locale Currency Mismatch" },
      { time: "00:06", level: "info", msg: "Scan complete. Duration: 2.4s" },
    ],
  },
  {
    id: "TEST-008",
    url: "https://app.example.com/docs",
    status: "passed",
    timestamp: "2026-04-25T15:00:00Z",
    duration: 1500,
    details: "Documentation pages loaded without issues.",
    testType: "full",
    streamLogs: [
      { time: "00:00", level: "info", msg: "Initializing Automated Intelligence Probe..." },
      { time: "00:01", level: "info", msg: "Connecting to https://app.example.com/docs..." },
      { time: "00:02", level: "success", msg: "Connection established. Starting scan..." },
      { time: "00:03", level: "info", msg: "Testing 24 documentation pages..." },
      { time: "00:04", level: "info", msg: "All pages loaded successfully" },
      { time: "00:05", level: "success", msg: "All checks passed." },
      { time: "00:05", level: "success", msg: "Scan complete. Duration: 1.5s" },
    ],
  },
  {
    id: "TEST-009",
    url: "https://app.example.com/products",
    status: "failed",
    timestamp: "2026-04-25T16:50:00Z",
    duration: 2800,
    bugId: "BUG-004",
    details: "Grid layout overlap at 900px viewport width.",
    testType: "full",
    streamLogs: [
      { time: "00:00", level: "info", msg: "Initializing Automated Intelligence Probe..." },
      { time: "00:01", level: "info", msg: "Connecting to https://app.example.com/products..." },
      { time: "00:02", level: "success", msg: "Connection established. Starting scan..." },
      { time: "00:03", level: "info", msg: "Phase 1: Responsive layout testing..." },
      { time: "00:04", level: "warn", msg: "Grid overflow detected at viewport 900px" },
      { time: "00:05", level: "error", msg: "Product cards overlapping in CSS grid between 768px-1024px" },
      { time: "00:06", level: "error", msg: "Bug BUG-004 created: CSS Grid Overlap in Product Gallery" },
      { time: "00:06", level: "info", msg: "Scan complete. Duration: 2.8s" },
    ],
  },
  {
    id: "TEST-010",
    url: "https://app.example.com/search",
    status: "failed",
    timestamp: "2026-04-24T11:18:00Z",
    duration: 1900,
    bugId: "BUG-005",
    details: "Null reference error in search autocomplete on rapid type+clear.",
    testType: "ai",
    streamLogs: [
      { time: "00:00", level: "info", msg: "Initializing AI Deep Scan..." },
      { time: "00:01", level: "info", msg: "Connecting to https://app.example.com/search..." },
      { time: "00:02", level: "success", msg: "Connection established. Starting scan..." },
      { time: "00:03", level: "info", msg: "Testing rapid input: typing 'test' → clearing immediately" },
      { time: "00:04", level: "error", msg: "TypeError: Cannot read property 'map' of null at SearchResults.render" },
      { time: "00:05", level: "error", msg: "Bug BUG-005 created: Null Reference in Search Autocomplete" },
      { time: "00:05", level: "info", msg: "Scan complete. Duration: 1.9s" },
    ],
  },
  {
    id: "TEST-011",
    url: "https://app.example.com/settings",
    status: "passed",
    timestamp: "2026-04-24T14:00:00Z",
    duration: 1100,
    details: "Settings page renders and saves preferences correctly.",
    testType: "full",
    streamLogs: [
      { time: "00:00", level: "info", msg: "Initializing Automated Intelligence Probe..." },
      { time: "00:01", level: "info", msg: "Connecting to https://app.example.com/settings..." },
      { time: "00:02", level: "success", msg: "Connection established. Starting scan..." },
      { time: "00:03", level: "info", msg: "Testing preference save: theme toggle → dark mode" },
      { time: "00:04", level: "info", msg: "Preference persisted successfully" },
      { time: "00:05", level: "success", msg: "All checks passed." },
      { time: "00:05", level: "success", msg: "Scan complete. Duration: 1.1s" },
    ],
  },
  {
    id: "TEST-012",
    url: "https://app.example.com/profile",
    status: "passed",
    timestamp: "2026-04-23T10:30:00Z",
    duration: 1350,
    details: "Profile page loads user data and avatar correctly.",
    testType: "full",
    streamLogs: [
      { time: "00:00", level: "info", msg: "Initializing Automated Intelligence Probe..." },
      { time: "00:01", level: "info", msg: "Connecting to https://app.example.com/profile..." },
      { time: "00:02", level: "success", msg: "Connection established. Starting scan..." },
      { time: "00:03", level: "info", msg: "User data loaded in 230ms" },
      { time: "00:04", level: "info", msg: "Avatar image loaded: 200 OK" },
      { time: "00:05", level: "success", msg: "All checks passed." },
      { time: "00:05", level: "success", msg: "Scan complete. Duration: 1.35s" },
    ],
  },
];

// ── Sample AI Findings ─────────────────────────────────────────────

export const sampleAIFindings: AIFinding[] = [
  {
    id: "AI-001",
    title: "Potential XSS vulnerability in search input",
    description: "The search input does not sanitize HTML entities before rendering in the autocomplete dropdown, potentially allowing script injection.",
    severity: "critical",
    codeSnippet: `// Vulnerable code:\ndropdown.innerHTML = results.map(r => \n  \`<div>\${r.title}</div>\`\n).join('');\n\n// Should use textContent or sanitize`,
    file: "src/components/Search.tsx:45",
    timestamp: "2026-04-28T09:15:00Z",
  },
  {
    id: "AI-002",
    title: "Memory leak in WebSocket connection handler",
    description: "Event listeners are attached on each reconnect attempt but never removed, causing memory accumulation over time.",
    severity: "high",
    codeSnippet: `// Missing cleanup:\nuseEffect(() => {\n  ws.on('message', handler);\n  // No return cleanup\n}, []);`,
    file: "src/hooks/useWebSocket.ts:23",
    timestamp: "2026-04-27T14:30:00Z",
  },
  {
    id: "AI-003",
    title: "Unoptimized database query in reports module",
    description: "The report generation uses SELECT * without pagination, loading entire tables into memory for large datasets.",
    severity: "high",
    codeSnippet: `// N+1 query detected:\nconst reports = await db.query(\n  'SELECT * FROM reports'\n);\nfor (const r of reports) {\n  r.items = await db.query(\n    'SELECT * FROM items WHERE report_id = ?',\n    [r.id]\n  );\n}`,
    file: "src/services/reports.ts:78",
    timestamp: "2026-04-26T11:00:00Z",
  },
  {
    id: "AI-004",
    title: "Missing error boundary in checkout flow",
    description: "The checkout flow lacks React Error Boundaries, causing the entire page to crash on component-level errors instead of showing a fallback UI.",
    severity: "medium",
    file: "src/pages/Checkout.tsx",
    timestamp: "2026-04-25T16:00:00Z",
  },
];
